/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as FirmwareRouteImport } from './routes/firmware'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LogRouteImport } from './routes/log'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as ApiCommandRouteImport } from './routes/api/command'
import { Route as ApiEpisodesRouteImport } from './routes/api/episodes'
import { Route as ApiMovesRouteImport } from './routes/api/moves'
import { Route as ApiSpecRouteImport } from './routes/api/spec'
import { Route as ApiEpisodesIdRouteImport } from './routes/api/episodes.$id'
import { Route as ApiMovesIdRouteImport } from './routes/api/moves.$id'
import { Route as ApiRecordStartRouteImport } from './routes/api/record.start'
import { Route as ApiRecordStopRouteImport } from './routes/api/record.stop'
import { Route as ApiMovesIdPlayRouteImport } from './routes/api/moves.$id.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmwareRoute = FirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommandRoute = ApiCommandRouteImport.update({
  id: '/api/command',
  path: '/api/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpisodesRoute = ApiEpisodesRouteImport.update({
  id: '/api/episodes',
  path: '/api/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMovesRoute = ApiMovesRouteImport.update({
  id: '/api/moves',
  path: '/api/moves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecRoute = ApiSpecRouteImport.update({
  id: '/api/spec',
  path: '/api/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpisodesIdRoute = ApiEpisodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEpisodesRoute,
} as any)
const ApiMovesIdRoute = ApiMovesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMovesRoute,
} as any)
const ApiRecordStartRoute = ApiRecordStartRouteImport.update({
  id: '/api/record/start',
  path: '/api/record/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordStopRoute = ApiRecordStopRouteImport.update({
  id: '/api/record/stop',
  path: '/api/record/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMovesIdPlayRoute = ApiMovesIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => ApiMovesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/firmware': typeof FirmwareRoute
  '/lab': typeof LabRoute
  '/log': typeof LogRoute
  '/spec': typeof SpecRoute
  '/api/command': typeof ApiCommandRoute
  '/api/episodes': typeof ApiEpisodesRouteWithChildren
  '/api/moves': typeof ApiMovesRouteWithChildren
  '/api/spec': typeof ApiSpecRoute
  '/api/episodes/$id': typeof ApiEpisodesIdRoute
  '/api/moves/$id': typeof ApiMovesIdRouteWithChildren
  '/api/record/start': typeof ApiRecordStartRoute
  '/api/record/stop': typeof ApiRecordStopRoute
  '/api/moves/$id/play': typeof ApiMovesIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/firmware': typeof FirmwareRoute
  '/lab': typeof LabRoute
  '/log': typeof LogRoute
  '/spec': typeof SpecRoute
  '/api/command': typeof ApiCommandRoute
  '/api/episodes': typeof ApiEpisodesRouteWithChildren
  '/api/moves': typeof ApiMovesRouteWithChildren
  '/api/spec': typeof ApiSpecRoute
  '/api/episodes/$id': typeof ApiEpisodesIdRoute
  '/api/moves/$id': typeof ApiMovesIdRouteWithChildren
  '/api/record/start': typeof ApiRecordStartRoute
  '/api/record/stop': typeof ApiRecordStopRoute
  '/api/moves/$id/play': typeof ApiMovesIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/firmware': typeof FirmwareRoute
  '/lab': typeof LabRoute
  '/log': typeof LogRoute
  '/spec': typeof SpecRoute
  '/api/command': typeof ApiCommandRoute
  '/api/episodes': typeof ApiEpisodesRouteWithChildren
  '/api/moves': typeof ApiMovesRouteWithChildren
  '/api/spec': typeof ApiSpecRoute
  '/api/episodes/$id': typeof ApiEpisodesIdRoute
  '/api/moves/$id': typeof ApiMovesIdRouteWithChildren
  '/api/record/start': typeof ApiRecordStartRoute
  '/api/record/stop': typeof ApiRecordStopRoute
  '/api/moves/$id/play': typeof ApiMovesIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crew'
    | '/firmware'
    | '/lab'
    | '/log'
    | '/spec'
    | '/api/command'
    | '/api/episodes'
    | '/api/moves'
    | '/api/spec'
    | '/api/episodes/$id'
    | '/api/moves/$id'
    | '/api/record/start'
    | '/api/record/stop'
    | '/api/moves/$id/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crew'
    | '/firmware'
    | '/lab'
    | '/log'
    | '/spec'
    | '/api/command'
    | '/api/episodes'
    | '/api/moves'
    | '/api/spec'
    | '/api/episodes/$id'
    | '/api/moves/$id'
    | '/api/record/start'
    | '/api/record/stop'
    | '/api/moves/$id/play'
  id:
    | '__root__'
    | '/'
    | '/crew'
    | '/firmware'
    | '/lab'
    | '/log'
    | '/spec'
    | '/api/command'
    | '/api/episodes'
    | '/api/moves'
    | '/api/spec'
    | '/api/episodes/$id'
    | '/api/moves/$id'
    | '/api/record/start'
    | '/api/record/stop'
    | '/api/moves/$id/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewRoute: typeof CrewRoute
  FirmwareRoute: typeof FirmwareRoute
  LabRoute: typeof LabRoute
  LogRoute: typeof LogRoute
  SpecRoute: typeof SpecRoute
  ApiCommandRoute: typeof ApiCommandRoute
  ApiEpisodesRoute: typeof ApiEpisodesRouteWithChildren
  ApiMovesRoute: typeof ApiMovesRouteWithChildren
  ApiSpecRoute: typeof ApiSpecRoute
  ApiRecordStartRoute: typeof ApiRecordStartRoute
  ApiRecordStopRoute: typeof ApiRecordStopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmware': {
      id: '/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof FirmwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/command': {
      id: '/api/command'
      path: '/api/command'
      fullPath: '/api/command'
      preLoaderRoute: typeof ApiCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/episodes': {
      id: '/api/episodes'
      path: '/api/episodes'
      fullPath: '/api/episodes'
      preLoaderRoute: typeof ApiEpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moves': {
      id: '/api/moves'
      path: '/api/moves'
      fullPath: '/api/moves'
      preLoaderRoute: typeof ApiMovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spec': {
      id: '/api/spec'
      path: '/api/spec'
      fullPath: '/api/spec'
      preLoaderRoute: typeof ApiSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/episodes/$id': {
      id: '/api/episodes/$id'
      path: '/$id'
      fullPath: '/api/episodes/$id'
      preLoaderRoute: typeof ApiEpisodesIdRouteImport
      parentRoute: typeof ApiEpisodesRoute
    }
    '/api/moves/$id': {
      id: '/api/moves/$id'
      path: '/$id'
      fullPath: '/api/moves/$id'
      preLoaderRoute: typeof ApiMovesIdRouteImport
      parentRoute: typeof ApiMovesRoute
    }
    '/api/record/start': {
      id: '/api/record/start'
      path: '/api/record/start'
      fullPath: '/api/record/start'
      preLoaderRoute: typeof ApiRecordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/record/stop': {
      id: '/api/record/stop'
      path: '/api/record/stop'
      fullPath: '/api/record/stop'
      preLoaderRoute: typeof ApiRecordStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moves/$id/play': {
      id: '/api/moves/$id/play'
      path: '/play'
      fullPath: '/api/moves/$id/play'
      preLoaderRoute: typeof ApiMovesIdPlayRouteImport
      parentRoute: typeof ApiMovesIdRoute
    }
  }
}

interface ApiEpisodesRouteChildren {
  ApiEpisodesIdRoute: typeof ApiEpisodesIdRoute
}

const ApiEpisodesRouteChildren: ApiEpisodesRouteChildren = {
  ApiEpisodesIdRoute: ApiEpisodesIdRoute,
}

const ApiEpisodesRouteWithChildren = ApiEpisodesRoute._addFileChildren(
  ApiEpisodesRouteChildren,
)

interface ApiMovesIdRouteChildren {
  ApiMovesIdPlayRoute: typeof ApiMovesIdPlayRoute
}

const ApiMovesIdRouteChildren: ApiMovesIdRouteChildren = {
  ApiMovesIdPlayRoute: ApiMovesIdPlayRoute,
}

const ApiMovesIdRouteWithChildren = ApiMovesIdRoute._addFileChildren(
  ApiMovesIdRouteChildren,
)

interface ApiMovesRouteChildren {
  ApiMovesIdRoute: typeof ApiMovesIdRouteWithChildren
}

const ApiMovesRouteChildren: ApiMovesRouteChildren = {
  ApiMovesIdRoute: ApiMovesIdRouteWithChildren,
}

const ApiMovesRouteWithChildren = ApiMovesRoute._addFileChildren(
  ApiMovesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewRoute: CrewRoute,
  FirmwareRoute: FirmwareRoute,
  LabRoute: LabRoute,
  LogRoute: LogRoute,
  SpecRoute: SpecRoute,
  ApiCommandRoute: ApiCommandRoute,
  ApiEpisodesRoute: ApiEpisodesRouteWithChildren,
  ApiMovesRoute: ApiMovesRouteWithChildren,
  ApiSpecRoute: ApiSpecRoute,
  ApiRecordStartRoute: ApiRecordStartRoute,
  ApiRecordStopRoute: ApiRecordStopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
